name: CI
on:
  push:
    branches: [ master, main]
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Cancel other workflows"
        uses: potiuk/cancel-workflow-runs@master
        with:
          cancelMode: allDuplicates
          cancelFutureDuplicates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          workflowFileName: main.yml

      - name: Install project dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.1
          dev: no
          php_extensions: json
          
      - name: Set env
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        
      - name: Create ZIP archive
        run: |
          mkdir ${{ env.REPOSITORY_NAME }}
          rsync -av --exclude='./${{ env.REPOSITORY_NAME }}' ./ ./${{ env.REPOSITORY_NAME }}
          find ./${{ env.REPOSITORY_NAME }} -path '*/.*' -prune -o -type f -print | zip ./build.zip -@
          rm -rf ${{ env.REPOSITORY_NAME }}
          
      - name: Deploy ZIP archive to bitter.de
        run: |
          curl -i -X POST -H "Content-Type: multipart/form-data" -F \
            'file=@build.zip' \
            https://www.bitter.de/api/v1/addons/update/${{ env.REPOSITORY_NAME }}
